# -*- coding: utf-8 -*-
"""SparkTutorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yaEjUbGg-XB_wxJglhqZ6EJ3Nn6zUgPr
"""

from pyspark.sql import SparkSession

spark=SparkSession.builder.appName('Dataframe').getOrCreate()

spark

## read the dataset
df_pyspark=spark.read.option('header','true').csv('test1.csv',inferSchema=True)

### Check the schema
df_pyspark.printSchema()

type(df_pyspark)

df_pyspark.head(3)

df_pyspark.show()

df_pyspark.select(['Name','Experience']).show()

df_pyspark['Name']

df_pyspark.describe().show()

df_pyspark=df_pyspark.withColumn('Experience After 2 year',df_pyspark['Experience']+2)

df_pyspark.show()

df_pyspark.withColumnRenamed('Name','New Name').show()